Repository binaural-dev/odoo-venezuela, pull requests merged in 2025-09, with the labels that each got.

#237 l10nve_17.0-fix_ti_8937-advance_concile_error
  l10n_ve_igtf/__manifest__.py
  l10n_ve_igtf/models/account_tax.py
Labels: 17.0, ✅ Validado, fix

#203 IMP #56191: l10n_invoice_digital
  l10n_ve_invoice_digital/__manifest__.py
  l10n_ve_invoice_digital/data/payment_method_data_tfhka.xml
  l10n_ve_invoice_digital/i18n/es_VE.po
  l10n_ve_invoice_digital/migrations/17.0.0.0.5/post-migration_l10n_ve_invoice_digital.py
  l10n_ve_invoice_digital/migrations/17.0.0.0.5/pre-migrations.py
  l10n_ve_invoice_digital/models/__init__.py
  l10n_ve_invoice_digital/models/account_journal.py
  l10n_ve_invoice_digital/models/account_move.py
  l10n_ve_invoice_digital/models/account_retention.py
  l10n_ve_invoice_digital/models/payment_method_tfhka.py
  l10n_ve_invoice_digital/security/ir.model.access.csv
  l10n_ve_invoice_digital/views/payment_method_tfhka.xml
  l10n_ve_stock/i18n/es_VE.po
  l10n_ve_stock_account/views/res_config_setting_views.xml
Labels: 17.0, ✅ Validado

#178 FIX #8663: l10n_ve_accountant
  l10n_ve_accountant/models/account_move.py
Labels: 17.0, ✅ Validado

#256 Fixing foreign price in sale and invoices
  l10n_ve_accountant/__manifest__.py
  l10n_ve_accountant/models/account_move.py
  l10n_ve_accountant/models/account_move_line.py
  l10n_ve_accountant/views/account_move.xml
  l10n_ve_accountant/views/account_move_line.xml
  l10n_ve_sale/__manifest__.py
  l10n_ve_sale/models/sale_order.py
  l10n_ve_sale/models/sale_order_line.py
  l10n_ve_sale/views/sale_order.xml
Labels: 17.0, ✅ Validado, fix

#280 FIX #56318: l10n_ve_stock_reports
  l10n_ve_stock_reports/__manifest__.py
  l10n_ve_stock_reports/tests/__init__.py
  l10n_ve_stock_reports/tests/test_controller.py
  l10n_ve_stock_reports/tests/test_wizards.py
  l10n_ve_stock_reports/wizard/stock_book_report.py
Labels: ✅ Validado, 18.0, ❌ Cambios funcionales, ⚙️ Cambios técnicos

#260 Create group for controling odoo studio visibility
  l10n_binaural_hide_studio_menu/__manifest__.py
  l10n_binaural_hide_studio_menu/i18n/es_VE.pot
  l10n_binaural_hide_studio_menu/security/groups.xml
  l10n_binaural_hide_studio_menu/static/description/icon.png
  l10n_binaural_hide_studio_menu/static/src/js/form_arch_parser.js
  l10n_ve_igtf/models/account_move.py
Labels: feat, 17.0, 🚧 Por validar

#170 FIX #8679: l10n_ve_invoice, l10n_ve_payment_extension
  l10n_ve_invoice/i18n/es_VE.po
  l10n_ve_invoice/models/account_move.py
  l10n_ve_invoice/tests/test_account_move.py
  l10n_ve_payment_extension/tests/test_retention_bs.py
Labels: 17.0, ✅ Validado, fix
