Repository binaural-dev/odoo-venezuela, pull requests merged in 2025-07, with the labels that each got.

#112 FIX #8177: l10n_ve_stock_account
  l10n_ve_stock_account/__manifest__.py
  l10n_ve_stock_account/views/stock_picking_views.xml
Labels: 17.0

#119 HOTFIX #8360: l10n_ve_sale
  l10n_ve_sale/__manifest__.py
  l10n_ve_sale/models/sale_order.py
Labels: 17.0

#123 FIX #8379: l10n_ve_stock_account
  l10n_ve_sale/__manifest__.py
  l10n_ve_sale/views/sale_order.xml
  l10n_ve_stock_account/__manifest__.py
  l10n_ve_stock_account/models/stock_picking.py
Labels: Validada

#132 Odoove 17.0 fix ti 8392 required fields not in view
  l10n_ve_accountant/__manifest__.py
  l10n_ve_accountant/i18n/es_VE.po
  l10n_ve_contact/tests/__init__.py
  l10n_ve_contact/tests/test_l1on_ve_contact.py
  l10n_ve_location/__manifest__.py
  l10n_ve_location/views/res_partner_views.xml
Labels: Validada

#141 FEAT #54057: l10n_ve_invoice_digital
  l10n_ve_invoice_digital/__manifest__.py
  l10n_ve_invoice_digital/models/account_move.py
Labels: En validacion, 17.0

#137 FEAT #8459: l10n_ve_payment_extension
  l10n_ve_payment_extension/i18n/es_VE.po
  l10n_ve_payment_extension/models/account_retention.py
  l10n_ve_payment_extension/tests/__init__.py
  l10n_ve_payment_extension/tests/common.py
  l10n_ve_payment_extension/tests/test_islr_retention_bs.py
  l10n_ve_payment_extension/tests/test_iva_retention_bs.py
  l10n_ve_payment_extension/tests/test_iva_retention_usd.py
  l10n_ve_payment_extension/tests/test_retention_bs.py
  l10n_ve_payment_extension/views/account_retention_islr.xml
Labels: Validada
