Repository binaural-dev/odoo-venezuela, pull requests merged in 2025-08, with the labels that each got.

#148 FIX #8569: stock_warehouse
  l10n_ve_stock/models/stock_warehouse.py
Labels: En validacion, 17.0

#174 FEAT #8701: l10n_ve_stock_account
  l10n_ve_stock_account/__manifest__.py
  l10n_ve_stock_account/report/report_invoice_free_form.xml
Labels: 17.0, ✅ Validado

#179 FEAT #8701: l10n_ve_stock_account
  l10n_ve_stock_account/report/report_invoice_free_form.xml
Labels: ✅ Validado, 18.0

#173 Fix error when cancel a mrp picking
  l10n_ve_stock_account/models/stock_picking.py
Labels: 17.0, 🚧 Por validar

#182 FIX #8715: l10n_ve_accountant
  l10n_ve_accountant/__manifest__.py
  l10n_ve_accountant/models/account_move.py
  l10n_ve_accountant/tests/__init__.py
  l10n_ve_accountant/tests/test_accountant.py
Labels: 17.0, ✅ Validado

#200 FIX #8838: l10n_ve_stock_account
  l10n_ve_stock_account/__manifest__.py
  l10n_ve_stock_account/models/stock_location.py
Labels: 17.0, ✅ Validado, fix

#195 Add config to allow internal picking with optional guide and fix view…
  l10n_ve_stock/__manifest__.py
  l10n_ve_stock/i18n/es_VE.po
  l10n_ve_stock/views/res_config_settings_views.xml
  l10n_ve_stock_account/__manifest__.py
  l10n_ve_stock_account/i18n/es_VE.po
  l10n_ve_stock_account/models/res_company.py
  l10n_ve_stock_account/models/res_config_settings.py
  l10n_ve_stock_account/models/stock_picking.py
  l10n_ve_stock_account/views/res_config_setting_views.xml
  l10n_ve_stock_account/views/stock_picking_views.xml
Labels: 17.0, ✅ Validado

#199 FEAT #8659: l10n_ve_accountant
  l10n_ve_accountant/tests/test_form_account_move.py
Labels: ✅ Validado, 18.0

#239 Dev 18 fix 55243 l10n ve rate
  l10n_ve_rate/__manifest__.py
  l10n_ve_rate/i18n/es_VE.po
  l10n_ve_rate/models/res_company.py
  l10n_ve_rate/models/res_config_settings.py
Labels: 18.0

#236 FIX_l10n_ve_stock#55243
  l10n_ve_stock/__manifest__.py
  l10n_ve_stock/models/product_template.py
  l10n_ve_stock/tests/test_stock.py
Labels: 18.0

#204 MIG #55248: l10n_ve_payment_extension
  l10n_ve_payment_extension/__manifest__.py
  l10n_ve_payment_extension/i18n/es_VE.po
  l10n_ve_payment_extension/models/account_move.py
  l10n_ve_payment_extension/models/account_payment.py
  l10n_ve_payment_extension/models/account_retention.py
  l10n_ve_payment_extension/models/account_retention_line.py
  l10n_ve_payment_extension/report/retention_line_report_views.xml
  l10n_ve_payment_extension/tests/test_retention_bs.py
  l10n_ve_payment_extension/views/account_move.xml
  l10n_ve_payment_extension/views/account_payment.xml
  l10n_ve_payment_extension/views/account_retention_islr.xml
  l10n_ve_payment_extension/views/account_retention_iva.xml
  l10n_ve_payment_extension/views/account_retention_line.xml
  l10n_ve_payment_extension/views/account_retention_municipal.xml
  l10n_ve_payment_extension/views/economic_activity.xml
  l10n_ve_payment_extension/views/economic_branch.xml
  l10n_ve_payment_extension/views/fees_retention.xml
  l10n_ve_payment_extension/views/payment_concept.xml
  l10n_ve_payment_extension/views/signature_config.xml
  l10n_ve_payment_extension/views/type_withholding.xml
  l10n_ve_payment_extension/wizard/account_payment_register.py
  l10n_ve_payment_extension/wizard/account_payment_register.xml
  l10n_ve_rate/models/res_config_settings.py
Labels: 18.0

#220 FEAT #56465: l10n_binaural
  l10n_binaural/__manifest__.py
  l10n_ve_accountant/models/account_invoice_report.py
Labels: 18.0
